# imbalance dataset:

a dataset with an unequal class distribution.

In [ ]:
# importing the dependencies
import numpy as np
import pandas as pd

In [ ]:
# load the dataset to pandas dataframe
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [ ]:
# first five row of dataframe
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
213964,139469.0,-0.313355,1.038943,-0.093972,-0.540988,0.042780,-1.106101,0.603947,0.287733,-0.100080,...,-0.217842,-0.621741,0.153701,-0.042585,-0.503706,0.148254,0.118168,0.032668,9.12,0.0
213965,139469.0,2.030213,0.285221,-1.938915,1.027250,0.851942,-0.701464,0.615953,-0.241818,-0.349579,...,0.167846,0.510669,0.027440,0.689138,0.427077,-0.532637,-0.040637,-0.068185,2.90,0.0
213966,139470.0,0.142229,0.672251,0.983900,-0.293528,0.068882,-0.487888,0.491696,-0.118390,0.318579,...,0.000967,0.224127,0.213429,-0.107864,-1.475182,-0.749164,0.330808,0.289856,8.57,0.0
213967,139471.0,2.144033,-1.953243,-0.578686,-1.849212,-1.376208,0.807803,-1.911412,0.306645,-0.726623,...,-0.124630,-0.092680,0.193302,-0.404247,-0.484276,-0.247000,0.034838,-0.033122,84.00,0.0
213968,139471.0,2.157143,-0.687990,-2.032580,-0.940456,-0.215889,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# determine the distribution of two classes

In [ ]:
credit_card_data['Class'].value_counts()

Class
0.0    213570
1.0       398
Name: count, dtype: int64

this is highly imbalance dataset.


0------> legit transaction

1------> fraudulent transaction

In [ ]:
# separating the legit and fraudulent transaction
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(213570, 31)
(398, 31)

# under-sampling

buid a sample dataset containing similar distribution of legit and fraud transaction.


number of fraud transaction---> 398

In [ ]:
legit_sample = legit.sample(n=398)

In [ ]:
print(legit_sample.shape)

(398, 31)

# concatenate two dataframes

In [ ]:
new_dataset = pd.concat([legit_sample, fraud] , axis = 0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
156570,108415.0,-0.364583,0.852269,0.078534,-0.789441,1.256161,0.955687,0.511170,0.369840,1.263055,...,-0.331418,-0.410681,0.138719,-1.500555,-0.689646,0.209183,0.373408,0.129701,8.98,0.0
109999,71634.0,-0.735848,0.866414,1.546357,0.620099,0.084980,-0.037646,0.572899,-0.099549,0.349912,...,-0.214607,-0.071308,-0.020700,0.107751,-0.357010,0.353911,0.178035,0.074134,9.92,0.0
69284,53350.0,0.992500,0.006540,1.557059,2.620151,-0.797437,0.801594,-0.810833,0.516264,0.051820,...,-0.000541,0.041728,0.090950,0.186642,0.112385,-0.040862,0.043187,0.023991,16.73,0.0
147945,89188.0,1.910647,-0.409704,-0.278401,0.647107,-0.718012,-0.610835,-0.442628,-0.172730,0.940186,...,0.295495,1.034764,0.058391,0.143017,-0.148643,0.449441,-0.009200,-0.035872,49.99,0.0
22572,32314.0,-0.889173,0.807213,2.222545,-0.338418,-0.028145,-1.365757,0.742181,-0.084014,-0.537143,...,-0.166038,-0.684350,-0.079144,0.879689,0.133274,-0.020475,-0.023434,0.067815,1.98,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
208651,137211.0,0.630579,1.183631,-5.066283,2.179903,-0.703376,-0.103614,-3.490350,1.094734,-0.717418,...,0.621622,0.043807,0.102711,-0.601505,0.127371,-0.163009,0.853792,0.356503,39.45,1.0
212516,138894.0,-1.298443,1.948100,-4.509947,1.305805,-0.019486,-0.509238,-2.643398,1.283545,-2.515356,...,1.178032,1.360989,-0.272013,-0.325948,0.290703,0.841295,0.643094,0.201156,0.01,1.0
212644,138942.0,-2.356348,1.746360,-6.374624,1.772205,-3.439294,1.457811,-0.362577,1.443791,-1.927359,...,0.857942,0.621203,0.964817,-0.619437,-1.732613,0.108361,1.130828,0.415703,727.91,1.0
213092,139107.0,-4.666500,-3.952320,0.206094,5.153525,5.229469,0.939040,-0.635033,-0.704506,-0.234786,...,-0.664263,1.821422,0.113563,-0.759673,-0.502304,0.630639,-0.513880,0.729526,22.47,1.0
213116,139117.0,-3.975939,-1.244939,-3.707414,4.544772,4.050676,-3.407679,-5.063118,1.007042,-3.190158,...,1.059737,-0.037395,0.348707,-0.162929,0.410531,-0.123612,0.877424,0.667568,8.30,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    398
1.0    398
Name: count, dtype: int64