# hyperparameter Tuning:

1. gridsearchCV
2. randomizedsearchCV

In [ ]:
# importing the dependencies
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

working on breast cancer dataset

In [ ]:
# loading dataset
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [ ]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]), 'frame': None, 'target_names': array(['malignant', 'benign'], dtype='<U9'), 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n', 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23'), 'filename': 'breast_cancer.csv', 'data_module': 'sklearn.datasets.data'}

In [ ]:
# loading data to dataframe
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [ ]:
data_frame.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
data_frame.shape

(569, 30)

In [ ]:
data_frame.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [ ]:
data_frame['label'] = breast_cancer_dataset.target

separating features and target

In [ ]:
x = data_frame.drop(columns = 'label' , axis = 1)
y = data_frame['label']

In [ ]:
print(x)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64

In [ ]:
x = np.asarray(x)
y = np.asarray(y)

# gridsearchCV

gridsearchCV is used to determine the best parameter for our model

In [ ]:
# load the svc model
model = SVC(

)

In [ ]:
# hyperparameters

parameters = {
    'kernel': ['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

In [ ]:
# gridsearch
classifier = GridSearchCV(model,parameters , cv =5)

In [ ]:
# fitting data in model
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([1.68819900e+00, 4.16450500e-03, 4.89997864e-03, 1.53800011e-02,
        3.15965590e+00, 4.03876305e-03, 4.81448174e-03, 1.51771069e-02,
        6.20138063e+00, 4.31485176e-03, 4.30574417e-03, 1.36445522e-02,
        7.54379153e+00, 4.65383530e-03, 4.21776772e-03, 1.35794163e-02]),
 'std_fit_time': array([4.17775981e-01, 9.36454521e-05, 2.32446450e-04, 6.28157872e-04,
        7.55330074e-01, 3.79371637e-04, 9.99889484e-04, 2.56918773e-03,
        3.15382247e+00, 1.92357398e-04, 1.82170243e-04, 5.70239998e-04,
        2.48101437e+00, 2.26533114e-04, 2.13768050e-04, 6.62992512e-04]),
 'mean_score_time': array([0.00160007, 0.00158668, 0.00213728, 0.00436721, 0.00181556,
        0.00146546, 0.00244136, 0.00384488, 0.0026103 , 0.0014009 ,
        0.00198035, 0.00356178, 0.00128579, 0.00141273, 0.00165825,
        0.00358939]),
 'std_score_time': array([1.97009206e-04, 3.88533050e-05, 1.96776085e-05, 3.11483872e-04,
        6.50592467e-04, 6.60261245e-05, 6.08072335e-04, 3.03693038e-04,
        2.77827408e-03, 5.83159173e-05, 1.95287574e-04, 4.59324144e-05,
        1.81112834e-04, 8.52950389e-05, 4.93277381e-05, 5.55737291e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.94736842, 0.84210526, 0.85087719, 0.54385965, 0.94736842,
        0.88596491, 0.88596491, 0.49122807, 0.93859649, 0.88596491,
        0.87719298, 0.48245614, 0.92982456, 0.87719298, 0.87719298,
        0.47368421]),
 'split1_test_score': array([0.92982456, 0.88596491, 0.89473684, 0.45614035, 0.93859649,
        0.9122807 , 0.92982456, 0.42105263, 0.93859649, 0.92105263,
        0.92105263, 0.40350877, 0.95614035, 0.92105263, 0.92105263,
        0.40350877]),
 'split2_test_score': array([0.97368421, 0.92982456, 0.92982456, 0.46491228, 0.97368421,
        0.92105263, 0.93859649, 0.42105263, 0.97368421, 0.90350877,
        0.9122807 , 0.42105263, 0.95614035, 0.90350877, 0.92105263,
        0.42105263]),
 'split3_test_score': array([0.92105263, 0.94736842, 0.94736842, 0.38596491, 0.92982456,
        0.93859649, 0.94736842, 0.35087719, 0.94736842, 0.93859649,
        0.95614035, 0.34210526, 0.93859649, 0.93859649, 0.94736842,
        0.34210526]),
 'split4_test_score': array([0.95575221, 0.9380531 , 0.9380531 , 0.45132743, 0.96460177,
        0.95575221, 0.95575221, 0.37168142, 0.96460177, 0.95575221,
        0.94690265, 0.36283186, 0.96460177, 0.95575221, 0.9380531 ,
        0.3539823 ]),
 'mean_test_score': array([0.94553641, 0.90866325, 0.91217202, 0.46044093, 0.95081509,
        0.92272939, 0.93150132, 0.41117839, 0.95256948, 0.920975  ,
        0.92271386, 0.40239093, 0.9490607 , 0.91922062, 0.92094395,
        0.39886664]),
 'std_test_score': array([0.01868869, 0.03938232, 0.03544367, 0.05025317, 0.01621632,
        0.02368918, 0.02435811, 0.04857818, 0.01419963, 0.02470123,
        0.02787898, 0.0489065 , 0.01281637, 0.02730027, 0.02410455,
        0.0476401 ]),
 'rank_test_score': array([ 4, 12, 11, 13,  2,  6,  5, 14,  1,  8,  7, 15,  3, 10,  9, 16],
       dtype=int32)}

In [ ]:
# best parameter
best_parameter = classifier.best_params_
print(best_parameter)

{'C': 10, 'kernel': 'linear'}

In [ ]:
# determine highest accuracy
highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9525694767893185

In [ ]:
# laoding the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [ ]:
result.head(

)

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       1.688199      0.417776  ...        0.018689                4
1       0.004165      0.000094  ...        0.039382               12
2       0.004900      0.000232  ...        0.035444               11
3       0.015380      0.000628  ...        0.050253               13
4       3.159656      0.755330  ...        0.016216                2

[5 rows x 15 columns]

In [ ]:
grid_search_result = result[['param_C','param_kernel','mean_test_score']]

In [ ]:
grid_search_result

    param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867

hifghest accuracy is 95.2

best parameter = {'C' :10 , 'kernel':'linear'}

# randomized searchcv

In [ ]:
# load the svc model
model = SVC(

)

In [ ]:
# hyperparameters

parameters = {
    'kernel': ['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

In [ ]:
# grid search
classifier = RandomizedSearchCV(model,parameters , cv =5)

In [ ]:
# fitting data in model
classifier.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00457921, 0.01403384, 0.02737885, 0.01275473, 0.01648116,
        1.6933022 , 0.00391488, 0.00413661, 0.01388292, 0.00455728]),
 'std_fit_time': array([3.00470020e-04, 5.53763484e-04, 6.69565588e-03, 1.14214623e-03,
        5.55172222e-03, 6.69412802e-01, 2.05015103e-04, 7.23042068e-05,
        4.79990958e-04, 1.96120323e-04]),
 'mean_score_time': array([0.0019331 , 0.00367479, 0.00702958, 0.00482812, 0.00734086,
        0.00124555, 0.00159984, 0.00173011, 0.00374465, 0.0013422 ]),
 'std_score_time': array([5.39294183e-05, 1.24869568e-04, 1.80632307e-03, 2.61540738e-03,
        2.88470886e-03, 2.52085907e-05, 3.51175575e-04, 3.47985291e-05,
        1.36248106e-04, 2.99780813e-05]),
 'param_kernel': masked_array(data=['rbf', 'sigmoid', 'sigmoid', 'poly', 'rbf', 'linear',
                    'poly', 'rbf', 'sigmoid', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[5, 10, 20, 10, 20, 1, 1, 10, 5, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 5},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'sigmoid', 'C': 20},
  {'kernel': 'poly', 'C': 10},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'poly', 'C': 1},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'sigmoid', 'C': 5},
  {'kernel': 'poly', 'C': 20}],
 'split0_test_score': array([0.88596491, 0.48245614, 0.47368421, 0.88596491, 0.87719298,
        0.94736842, 0.84210526, 0.87719298, 0.49122807, 0.87719298]),
 'split1_test_score': array([0.92982456, 0.40350877, 0.40350877, 0.92105263, 0.92105263,
        0.92982456, 0.88596491, 0.92105263, 0.42105263, 0.92105263]),
 'split2_test_score': array([0.93859649, 0.42105263, 0.42105263, 0.90350877, 0.92105263,
        0.97368421, 0.92982456, 0.9122807 , 0.42105263, 0.90350877]),
 'split3_test_score': array([0.94736842, 0.34210526, 0.34210526, 0.93859649, 0.94736842,
        0.92105263, 0.94736842, 0.95614035, 0.35087719, 0.93859649]),
 'split4_test_score': array([0.95575221, 0.36283186, 0.3539823 , 0.95575221, 0.9380531 ,
        0.95575221, 0.9380531 , 0.94690265, 0.37168142, 0.95575221]),
 'mean_test_score': array([0.93150132, 0.40239093, 0.39886664, 0.920975  , 0.92094395,
        0.94553641, 0.90866325, 0.92271386, 0.41117839, 0.91922062]),
 'std_test_score': array([0.02435811, 0.0489065 , 0.0476401 , 0.02470123, 0.02410455,
        0.01868869, 0.03938232, 0.02787898, 0.04857818, 0.02730027]),
 'rank_test_score': array([ 2,  9, 10,  4,  5,  1,  7,  3,  8,  6], dtype=int32)}

In [ ]:
# best parameter
best_parameter = classifier.best_params_
print(best_parameter)

{'kernel': 'linear', 'C': 1}

In [ ]:
# determine highest accuracy
highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9455364073901569

In [ ]:
# laoding the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [ ]:
result.head(

)

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.004579      0.000300  ...        0.024358                2
1       0.014034      0.000554  ...        0.048906                9
2       0.027379      0.006696  ...        0.047640               10
3       0.012755      0.001142  ...        0.024701                4
4       0.016481      0.005552  ...        0.024105                5

[5 rows x 15 columns]

In [ ]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]

In [ ]:
randomized_search_result

   param_C param_kernel  mean_test_score
0        5          rbf         0.931501
1       10      sigmoid         0.402391
2       20      sigmoid         0.398867
3       10         poly         0.920975
4       20          rbf         0.920944
5        1       linear         0.945536
6        1         poly         0.908663
7       10          rbf         0.922714
8        5      sigmoid         0.411178
9       20         poly         0.919221